### ISSUE TITLE
Changes to be considered for Duties section

### ISSUE THREAD

**Issue by vboyce** [tech-squares/govdocs#10]
? Standing policy review for President

? Rooming is in charge of event reg

? Booking needs to provide info to treasurer to ensure people get paid

**Comment by vboyce** [comment]
I'm fine with not adding any SP review comment to president section. 

Proposal for rooming The Rooming Director shall reserve rooms "and handle event registration" for weekly dances and other club functions, and help other club officers with rooming-related needs.

Booking: add bullet point saying "coordinate with the Treasurer to ensure payment of callers & cuers" or something similar

**Comment by dehnert** [comment]
Resolved in our fall 2016 review cycle.
