### ISSUE TITLE
Allow candidates in elections to vote (especially for multi-candidate elections)

### ISSUE THREAD

**Issue by kchen** [tech-squares/govdocs#2]
We don't have a particularly good todo list, so Alex suggested I file a ticket here.

The standing policies should allow candidates to vote for the election they are running in, especially for multi-candidate elections like member-at-large where the assumption that the candidate is voting for themselves is not fully accurate, since they may want to vote for some, but not all of the other candidates, as well.

The current constitution and standing policies do not appear to say anything about the issue.

This is particularly relevant for student voters, who have a lot more voting power.  This may also make the student have to decide between exercising their vote or running for the office.

**Comment by vboyce** [comment]
We should say in SP that candidates are allowed to vote (on paper, from the hallway) in their own elections.

**Comment by dehnert** [comment]
Resolved in our fall 2016 review cycle.
