### ISSUE TITLE
Clarify absentee voting

### ISSUE THREAD

**Issue by kchen** [tech-squares/govdocs#3]
Alex suggests clarifying absentee voting, or more specifically, that it is not permitted.

**Comment by dehnert** [comment]
This died in an argument about what we actually wanted. We should maybe have that discussion on t-s-d at some point, or something. See also https://mailman.mit.edu:444/mailman/private/tech-squares-discuss/2016-April/000559.html (and Naha's reply) and https://mailman.mit.edu:444/mailman/private/tech-squares/2016-April/000752.html (and the linked minutes).

**Comment by vboyce** [comment]
We should definitely not allow absentee voting, which probably means we should try to codify this.

**Comment by dehnert** [comment]
Resolved in our fall 2016 review cycle.
