### ISSUE TITLE
Clarify procedure for proposing standing policies

### ISSUE THREAD

**Issue by kchen** [tech-squares/govdocs#4]
The constitution indicates how an individual can propose a constitutional amendment, but the standing policies do not specify a clear procedure for an individual to propose a new standing policy or to propose amending a standing policy.

**Comment by vboyce** [comment]
Alex notes that we should also clarify that in the petition of 5 voting members they can set agenda items for the club meeting that gets forced.

**Comment by dehnert** [comment]
Per https://github.com/tech-squares/govdocs/pull/1#issuecomment-210743527, this is resolved.

**Comment by dehnert** [comment]
Per https://github.com/tech-squares/govdocs/pull/1#issuecomment-210743527, this is resolved.
