### ISSUE TITLE
Clarify "it" in amendment handling clause

### ISSUE THREAD

**Issue by kchen** [tech-squares/govdocs#5]
The "Amendments" section of the constitution says:

"A proposed amendment to the constitution must be submitted in writing to the Executive Committee. It shall publicize the proposed amendment to the club at least four weeks before it will be voted on."

"It" is clear in context, although not clear upon initially reading the sentence. The next time a more important constitutional amendment is proposed, it would possibly be useful to change the sentences to say "... to the Executive Committee, which shall publicize ..."

**Comment by dehnert** [comment]
Resolved in our fall 2016 review cycle.
