### ISSUE TITLE
Wording clarification needed for article V

### ISSUE THREAD

**Issue by vboyce** [tech-squares/govdocs#8]

**Comment by vboyce** [comment]
clarification needed for how to hire/fire a (club) cuer/caller, and whether we're allowed to be without a club cuer/caller.

**Comment by vboyce** [comment]
Proposed change replace current sections 1-3 with 
Section 1: The club caller(s) shall be defined as the employee(s) who is hired to be primarily responsible for calling square dances at weekly dances.  The club cuer(s) shall be defined as the employee(s) who are hired to be primarily responsible for cueing round dances at weekly dances. 

Section 2. No person may be an Executive Committee member and club caller or club cuer concurrently.

no changes to the rest (but renumbering may be needed)

**Comment by dehnert** [comment]
Resolved in our fall 2016 review cycle.
